### ISSUE TITLE
広告主を絡めた友達紹介（友達紹介+広告主の案件利用）キャンペーン

### ISSUE THREAD

**Issue by rinokurasawa** [voyagegroup/github-approver-check#13]
■やりたいこと
AがBにオンワード・クローゼットを紹介し、
Bがオンワード・クローゼットで税抜3,000円以上の購入をした場合、
Aに5,000pts.（500円分）・Bに15,000pts.（1,500円分）をプレゼント

■確認いただきたいこと
・（紹介者と被紹介者を計測する方法がないので）そもそも実施可能か？
・可能な場合の計測方法は下記のようなイメージになるか？

＜計測のイメージ＞
下記URLをラストクリックした方が対象になるイメージでいるのですが、このようなログで計測可能でしょうか？
https://ecnavi.jp/ad/62791/show/?invite_id=◯◯&ecnframe=1058
※ナビ登録済みの人には、通常の広告主の案件ページ
※ナビ未登録の方には、広告主の案件ページ+会員登録のボタンがついているページ

**Comment by h-makino** [comment]
リポジトリが間違っているので、
* https://github.com/voyagegroup/ecnavi/issues/15689 に転載しました。

@rinokurasawa こちらのissueはクローズしておいてください。

**Comment by rinokurasawa** [comment]
チームから外れてしまっているみたいで、
https://github.com/voyagegroup/ecnavi/issues/15689 
のURLにログインできず今ご対応いただいているので追記いただき助かりますｍｍ

Issueはクローズいたしました。よろしくお願いいたします。
